[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- . ':!.claude' ':!.github' ':!.vscode' ':!audit' ':!tests' ':!.oxlintrc.json' ':!.prettierignore' ':!.prettierrc' ':!AGENTS.md' ':!CHANGELOG.md' ':!playwright.config.ts' ':!README.md' ':!stylelint.config.mjs' ':!vitest.config.ts'"
