import type { ComponentApi } from "../types"

export default {
  component: "Carousel",
  notes: {
    html: "The root is a `ul` with an `aria-label`. Buttons and markers are generated by CSS.",
  },
  options: [
    {
      default: '"start"',
      description: "Where items snap.",
      group: "Alignment",
      prop: "align",
      values: { center: ".ui-align-center", start: null },
    },
    {
      class: ".ui-with-buttons",
      default: "true",
      description:
        'Previous and next buttons. `"outside"` places them beside the items.',
      group: "Buttons",
      prop: "buttons",
      values: { outside: ".ui-buttons-outside" },
    },
    {
      attribute: "[aria-label]",
      description: "Accessible name of the carousel.",
      group: "Label",
      prop: "label",
    },
    {
      class: ".ui-with-markers",
      default: "false",
      description: "One marker per item, after the list.",
      group: "Markers",
      prop: "markers",
    },
    {
      class: ".ui-peek",
      default: "false",
      description: "Shows part of the neighbouring items.",
      group: "Peek",
      prop: "peek",
    },
    {
      class: ".ui-buttons-persistent",
      default: "false",
      description:
        "Keeps the buttons visible at the ends. A disabled button has a muted border.",
      group: "Persistent buttons",
      prop: "persistentButtons",
    },
    {
      cssVar: "--_per-view",
      default: "1",
      description: "Number of visible items.",
      group: "Items per view",
      prop: "perView",
    },
  ],
  parts: [
    {
      code: "<li>",
      description: "An item.",
      selector: ".ui-carousel > :first-child",
      slots: ["default"],
    },
    {
      code: "::scroll-button(inline-start)",
      description: "The previous button.",
      props: ["buttons"],
      selector: ".ui-carousel::scroll-button(inline-start)",
    },
    {
      code: "::scroll-button(inline-end)",
      description: "The next button.",
      props: ["buttons"],
      selector: ".ui-carousel::scroll-button(inline-end)",
    },
    {
      code: "li::scroll-marker",
      description: "A marker, one per item.",
      props: ["markers"],
      selector: ".ui-carousel > :first-child::scroll-marker",
    },
  ],
  root: {
    description: "The scroller.",
    selector: "ul.ui-carousel",
  },
  source: "Carousel",
} satisfies ComponentApi
