import type { FrameworkId } from "./framework-routing"

type Note = string | Partial<Record<FrameworkId | "default", string>>

const whatsNew = {
  accordion: [
    {
      astro: `<a href="#marker-animation">Marker animation</a> with the <code>markerAnimation</code> prop.`,
      html: `<a href="#marker-animation">Marker animation</a> with <code>.ui-marker-flip</code>, <code>.ui-marker-rotate</code> or <code>.ui-marker-turn</code>.`,
      vue: `<a href="#marker-animation">Marker animation</a> with the <code>markerAnimation</code> prop.`,
    },
    {
      astro: `A chevron marker by default. The <code>marker</code> slot replaces it.`,
      vue: `A chevron marker by default. The <code>marker</code> slot replaces it.`,
    },
    {
      html: `Breaking: markers only animate with a marker class. Add <code>.ui-marker-rotate</code> to keep the previous rotation.`,
    },
    `Borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  avatar: [
    `Size follows <code>--control-size</code> and the text uses <code>--primary-contrast</code>. See <a href="#api">CSS variables</a>.`,
  ],
  badge: [
    `Text uses <code>--primary-contrast</code>. See <a href="#api">CSS variables</a>.`,
  ],
  button: [
    {
      astro: `<a href="#icon-only">Icon-only</a> buttons are square. <code>rounded</code> makes them round and <code>ripple</code> adds a hover halo.`,
      html: `<a href="#icon-only">Icon-only</a> buttons are square. <code>.ui-rounded</code> makes them round and <code>.ui-ripple</code> adds a hover halo.`,
      vue: `<a href="#icon-only">Icon-only</a> buttons are square. <code>rounded</code> makes them round and <code>ripple</code> adds a hover halo.`,
    },
    `Replaces <code>IconButton</code>.`,
    `Wrap the label in a <code>&lt;span&gt;</code> to <a href="#buttons-with-icon-and-label">tighten the padding</a> next to an icon.`,
    {
      default: `Links with <code>aria-disabled="true"</code> look and act disabled.`,
      html: `Links with <code>.ui-disabled</code> or <code>aria-disabled="true"</code> look and act disabled.`,
    },
  ],
  "button-group": [
    `<a href="#split-button">Split button</a> with a <code>Menu</code>.`,
    `Icon-only buttons stay square.`,
    `Small groups are <code>--button-size-small</code> (32px), and borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  callout: [
    `Borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  card: [
    `Borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  carousel: [
    `New component. A scroll snap carousel with buttons and markers generated by CSS.`,
    `Buttons use <code>--surface-inverse</code> and <code>--text-inverse</code>. See <a href="#api">CSS variables</a>.`,
  ],
  checkbox: [
    `Borders follow <code>--field-border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  chip: [
    `Corners follow <code>--border-radius</code> (8px), and borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  "description-list": [
    `Borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  drawer: [
    {
      astro: `<code>DrawerHeader</code> takes a <code>commandfor</code> prop, so the close button works without JavaScript.`,
      vue: `<code>DrawerHeader</code> takes a <code>commandfor</code> prop, so the close button works without JavaScript.`,
    },
    `The backdrop dims and blurs like <code>Dialog</code>, through <code>--backdrop-color</code> and <code>--backdrop-blur</code>. See <a href="#api">CSS variables</a>.`,
  ],
  list: [
    `Item height follows <code>--control-size</code>, and borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  menu: [
    `New component. A popover menu that anchors to its trigger, with groups and submenus. HTML and CSS only.`,
  ],
  radio: [
    `The input is <code>--choice-size</code> (20px) like <code>Checkbox</code>, and borders follow <code>--field-border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  range: [
    `Invalid states use <code>--invalid-color</code>. See <a href="#api">CSS variables</a>.`,
  ],
  switch: [
    `Invalid states use <code>--invalid-color</code>, and borders follow <code>--field-border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  table: [
    `Borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  tabs: [
    `Restyled as a segmented control.`,
    {
      default: `<a href="#filled">Filled</a>, <a href="#line">line</a> and <a href="#outlined">outlined</a> variants with the <code>variant</code> prop.`,
      html: `<a href="#filled">Filled</a>, <a href="#line">line</a> and <a href="#outlined">outlined</a> variants with <code>.ui-filled</code>, <code>.ui-line</code> and <code>.ui-outlined</code>.`,
    },
  ],
  "text-field": [
    `Invalid states use <code>--invalid-color</code>, and borders follow <code>--field-border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  toast: [
    `Severity icons follow <code>--success</code>, <code>--info</code>, <code>--warning</code> and <code>--critical</code>. See <a href="#api">CSS variables</a>.`,
  ],
  toggle: [
    `<code>ToggleButton</code> and <code>ToggleGroup</code> borders follow <code>--border-width</code>. See <a href="#api">CSS variables</a>.`,
  ],
  tooltip: [
    `Uses <code>--surface-inverse</code> and <code>--text-inverse</code>. See <a href="#api">CSS variables</a>.`,
  ],
  typography: [
    `<a href="#classless">Rich text</a> spacing comes from one flow space, with more room above headings than below.`,
    `Heading sizes and line heights snap to <code>--rhythm-step</code>, and the heading scale no longer inverts on narrow screens.`,
    `<a href="#rich-text-showcase">Rich text</a> styles tables, <code>hr</code> and task lists.`,
  ],
} satisfies Record<string, Note[]>

export function whatsNewFor(framework: FrameworkId, slug: string) {
  const notes: Note[] = whatsNew[slug as keyof typeof whatsNew] ?? []

  return notes
    .map((note) =>
      typeof note === "string" ? note : (note[framework] ?? note.default),
    )
    .filter((note) => note !== undefined)
}
