import type { FrameworkId } from "./framework-routing"

type Note = string | Partial<Record<FrameworkId | "default", string>>

const whatsNew = {
  accordion: [
    {
      astro: `<a href="#marker-animation">Marker animation</a> with the <code>markerAnimation</code> prop.`,
      html: `<a href="#marker-animation">Marker animation</a> with <code>.ui-marker-flip</code>, <code>.ui-marker-rotate</code> or <code>.ui-marker-turn</code>.`,
      vue: `<a href="#marker-animation">Marker animation</a> with the <code>markerAnimation</code> prop.`,
    },
    {
      astro: `A chevron marker by default. The <code>marker</code> slot replaces it.`,
      vue: `A chevron marker by default. The <code>marker</code> slot replaces it.`,
    },
    {
      html: `Breaking: markers only animate with a marker class. Add <code>.ui-marker-rotate</code> to keep the previous rotation.`,
    },
  ],
  button: [
    {
      astro: `<a href="#icon-only">Icon-only</a> buttons are square. <code>rounded</code> makes them round and <code>ripple</code> adds a hover halo.`,
      html: `<a href="#icon-only">Icon-only</a> buttons are square. <code>.ui-rounded</code> makes them round and <code>.ui-ripple</code> adds a hover halo.`,
      vue: `<a href="#icon-only">Icon-only</a> buttons are square. <code>rounded</code> makes them round and <code>ripple</code> adds a hover halo.`,
    },
    `Replaces <code>IconButton</code>.`,
    `Wrap the label in a <code>&lt;span&gt;</code> to <a href="#buttons-with-icon-and-label">tighten the padding</a> next to an icon.`,
    {
      default: `Links with <code>aria-disabled="true"</code> look and act disabled.`,
      html: `Links with <code>.ui-disabled</code> or <code>aria-disabled="true"</code> look and act disabled.`,
    },
  ],
  "button-group": [
    `<a href="#split-button">Split button</a> with a <code>Menu</code>.`,
    `Icon-only buttons stay square.`,
  ],
  carousel: [
    `New component. A scroll snap carousel with buttons and markers generated by CSS.`,
  ],
  drawer: [
    {
      astro: `<code>DrawerHeader</code> takes a <code>commandfor</code> prop, so the close button works without JavaScript.`,
      vue: `<code>DrawerHeader</code> takes a <code>commandfor</code> prop, so the close button works without JavaScript.`,
    },
  ],
  menu: [
    `New component. A popover menu that anchors to its trigger, with groups and submenus. HTML and CSS only.`,
  ],
  tabs: [
    `Restyled as a segmented control.`,
    `<a href="#narrow-spaces">Shrinks to fit</a> narrow spaces, with an ellipsis on long labels.`,
    {
      default: `<a href="#filled">Filled</a>, <a href="#line">line</a> and <a href="#outlined">outlined</a> variants with the <code>variant</code> prop.`,
      html: `<a href="#filled">Filled</a>, <a href="#line">line</a> and <a href="#outlined">outlined</a> variants with <code>.ui-filled</code>, <code>.ui-line</code> and <code>.ui-outlined</code>.`,
    },
  ],
  typography: [
    `<a href="#classless">Rich text</a> spacing comes from one flow space, with more room above headings than below.`,
    `Heading sizes and line heights snap to <code>--rhythm-step</code>, and the heading scale no longer inverts on narrow screens.`,
    `<a href="#rich-text-showcase">Rich text</a> styles tables, <code>hr</code> and task lists.`,
  ],
} satisfies Record<string, Note[]>

export function whatsNewFor(framework: FrameworkId, slug: string) {
  const notes: Note[] = whatsNew[slug as keyof typeof whatsNew] ?? []

  return notes
    .map((note) =>
      typeof note === "string" ? note : (note[framework] ?? note.default),
    )
    .filter((note) => note !== undefined)
}
